// productsData.js
import ImgP from "@/public/image/product.avif";

export const productsData = [
  {
    id: 1,
    category: "Beauty",
    subCategory: "Collagen",
    title: "Collagen Peptides",
    description: "Supports skin elasticity and hydration.",
    image: ImgP,
    rating: 4.5,
    reviews: 120,
    type: "Powder",
    brand: "Vital Proteins",
    originalPrice: 30.0,
    discountedPrice: 25.0,
    badge: "BEST SELLER",
  },
  {
    id: 2,
    category: "Beauty",
    subCategory: "Biotin",
    title: "Biotin 5000mcg",
    description: "Promotes healthy hair, skin, and nails.",
    image: ImgP,
    rating: 4.7,
    reviews: 95,
    type: "Capsule",
    brand: "Nature's Bounty",
    originalPrice: 12.0,
    discountedPrice: 9.99,
    badge: "POPULAR",
  },
  {
    id: 3,
    category: "Beauty",
    subCategory: "Hair-Skin&Nails",
    title: "Hair, Skin & Nails Vitamins",
    description: "Supports overall beauty health.",
    image: ImgP,
    rating: 4.6,
    reviews: 150,
    type: "Tablet",
    brand: "Nature Made",
    originalPrice: 18.0,
    discountedPrice: 15.0,
    badge: "NEW",
  },
  {
    id: 4,
    category: "Beauty",
    subCategory: "Hair-Skin&Nails",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 5,
    category: "Beauty",
    subCategory: "Hair-Skin&Nails",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 6,
    category: "Beauty",
    subCategory: "Collagen",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 7,
    category: "Beauty",
    subCategory: "Collagen",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 8,
    category: "Beauty",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 9,
    category: "Beauty",
    subCategory: "Collagen",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 10,
    category: "Beauty",
    subCategory: "Collagen",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 11,
    category: "Beauty",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 12,
    category: "Beauty",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 13,
    category: "Beauty",
    subCategory: "Collagen",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 14,
    category: "Beauty",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 15,
    category: "Bone",
    subCategory: "Bone-Supplements",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 16,
    category: "Bone",
    subCategory: "Bone-Supplements",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 17,
    category: "Bone",
    subCategory: "Vitamin-K",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 18,
    category: "Bone",
    subCategory: "Vitamin-K",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 19,
    category: "Bone",
    subCategory: "Magnesium",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 20,
    category: "Bone",
    subCategory: "Magnesium",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 21,
    category: "joints",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 22,
    category: "joints",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 23,
    category: "joints",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 24,
    category: "joints",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 25,
    category: "joints",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 26,
    category: "Bojointsne",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 27,
    category: "joints",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 28,
    category: "joints",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 29,
    category: "joints",
    subCategory: "Biotin",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 30,
    category: "Bone",
    subCategory: "Vitamin-D",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 31,
    category: "Bone",
    subCategory: "Vitamin-D",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 32,
    category: "Bone",
    subCategory: "Calcium",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 33,
    category: "Bone",
    subCategory: "Calcium",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
  {
    id: 34,
    category: "Bone",
    subCategory: "Magnesium",
    title: "Vitamin C 1000mg",
    description: "Boosts immune system and skin health.",
    image: ImgP,
    rating: 4.8,
    reviews: 200,
    type: "Tablet",
    brand: "Nature's Way",
    originalPrice: 10.0,
    discountedPrice: 8.5,
    badge: "BEST SELLER",
  },
];
